<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Pytorch/blob/main/Basics/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## **Introductions to Tensors**

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
type(scalar)

torch.Tensor

In [4]:
# check the dimension of the scalar
scalar.ndim

0

In [5]:
# Check the shape of the scalar
scalar.shape

torch.Size([])

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
torch.tensor([[[[[8,8,6], [4,6,8]]], [[[4,8,6], [7,3,8]]]]]).shape

torch.Size([1, 2, 1, 2, 3])

In [10]:
torch.tensor([[[[[8,8,6], [4,6,8]]]]]).ndim

5

In [11]:
# Matrix
MATRIX = torch.tensor([[4,5],
                      [9,10]])
MATRIX

tensor([[ 4,  5],
        [ 9, 10]])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX.ndim

2

## **Creating Random Tensors with Pytorch**

Why random tensors?

Ans: Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

this adjustment is done through backpropagation.

In [14]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.8058, 0.8167, 0.3383, 0.3818],
         [0.4926, 0.8985, 0.3514, 0.3278],
         [0.1463, 0.3460, 0.6413, 0.8255]]])

In [15]:
random_tensor.ndim

3

In [16]:
random_tensor.shape

torch.Size([1, 3, 4])

## **Zeros and Ones**

In [17]:
# Create tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros.ndim, zeros.shape

(2, torch.Size([3, 4]))

In [19]:
# Create tensopr of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## **Creating range of Tensors and Tensor-like**

In [20]:
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
one_to_ten.ndim, one_to_ten.shape

(1, torch.Size([10]))

In [22]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor Datatypes**

**Note** : Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:

1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors on right device.  

In [23]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # What device is your tensor on
                               requires_grad=False # Whether or not to track gradients with this tensors operation
                               )
float_32_tensor

tensor([3., 6., 9.])

In [24]:
type(float_32_tensor), float_32_tensor.dtype

(torch.Tensor, torch.float32)

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Manipulating Tensors (Tensor operations)

Tensor operatiosn include:
* Addition
* Substraction
* Multiplication
* Division
* Matrix Multiplcation

In [26]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply Tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [28]:
# Pytorch also has in-built functions
torch.mul(tensor,10)

tensor([100, 200, 300])

## **Matrix Multiplcation**

Two main ways of performing multiplication in  neural networks and deep learning

1. Element wise multiplication
2. Matrix multiplication (dot product)

In [29]:
# Element wise matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

**Comparing the time difference if multiplcation donne with loop and using matmul function**

In [30]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 1.67 ms, sys: 0 ns, total: 1.67 ms
Wall time: 1.68 ms


In [31]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 96 µs, sys: 0 ns, total: 96 µs
Wall time: 101 µs


tensor(1400)

## **One of the most common errors in deep learning: shape errors**

In [32]:
# Shape for matrix multiplication
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_, tensor_b) # torch.mm() is same as torch.matmul()
torch.matmul(tensor_a, tensor_b)

RuntimeError: ignored

The above error shows that the shape of the tensors are not matching for the multiplication

In [33]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [34]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [35]:
# now let's do the multiplication once again
torch.matmul(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## **Tensor aggregation (mean, max,mean,sum)**

In [36]:
# Create tensor range
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
# Find the min, max and mean of the tensor
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [38]:
# In case of mean it has to be converted to long number or float
torch.mean(x.type(torch.float32))


tensor(45.)

In [39]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## **Finding the position min and max**

In [40]:
# Find the position in the tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [41]:
# find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [42]:
x[9]

tensor(90)

In [43]:
x_matrix = torch.tensor([[2,8,3],
                         [15,19,22],
                         [42,53,88]])
x_matrix.argmax()

tensor(8)

In [44]:
x_matrix.argmin()

tensor(0)

## **Reshaping, stacking, squeezing and unsqueezing tensors**

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensorof certain shape but keep the
memory of the original tensor.
* Stacking - combine multiple tensors
on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 imensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with the dimensions permuted (swapped) in a certain way


In [45]:
# Let'screate a tensor
x_float = torch.arange(1., 10.)
x_float

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
x_float.dim, x_float.shape

(<function Tensor.dim>, torch.Size([9]))

In [47]:
# Add an extra dimension
x_float_reshaped = x_float.reshape(3,3)

To keep in mind that above tensor has 9 elements in it. so we can reshape the element upto such that it;s multiple is 9

In [48]:
x_float_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [49]:
# Change the view
z = x_float_reshaped.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
# Changing z changes x_float_reshaped (because the view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [51]:
# Stack tensors on above of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [52]:
x_float_reshaped

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [53]:
x_float_reshaped.shape

torch.Size([3, 3])

In [54]:
x_float_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [55]:
x_float_reshaped.shape

torch.Size([3, 3])

**squeeze()** method removes all the single dimensions in the tensor.
In the above case there is no 1 dimension, therefore nothing is changed

In [56]:
x_float_reshaped = x_float_reshaped.reshape(1,9)

In [57]:
x_float_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In the above case we reshaped the tensor to have a 1 dimension, now when we squeeze the tensor it removes the 1 dimension

Let's reshape the above tensor too (3,3) and then check whether **unsqueeze()**
adds another dimension or not.

In [58]:
x_float_reshaped = x_float_reshaped.reshape(3,3)
x_float_reshaped

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [59]:
x_float_reshaped.unsqueeze(dim=1)

tensor([[[5., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])

## **Indexingwith PyTorch is similar to indexing with NumPy**

In [60]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [61]:
# Let's index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
# Let's index the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [65]:
# Let's index the inner most bracket (last dimension)
x[0][1][2]

tensor(6)

In [66]:
# We can also use ":" to select "all" of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [76]:
# Get all the values of the 0th and 1st dimension but only 1 of 2nd dimension
x[:,0:2,0:1]

tensor([[[1],
         [4]]])

In [68]:
# Get all the values of the 0 dimension but only 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [77]:
# Index on x to return 9
x[0][2][2]

tensor(9)

In [78]:
# Index on x to return 3,6,9
x[:,:, 2]

tensor([[3, 6, 9]])

## **PyTorch tensors & NumPy**

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to inetract with it

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor-> NumPy -> torch.Tensor.numpy()

In [79]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Warning: while converting from numpy -> pytorch, pytorch reflects numpy's default dtype of float64
# unless specified otherwise
tensor = torch.from_numpy(array).type(torch.float32)

In [85]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
numpy_tensor.dtype

dtype('float32')