<a href="https://colab.research.google.com/github/Priyo-prog/Deep-Learning-with-Pytorch/blob/main/Basics/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## **Introductions to Tensors**

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
type(scalar)

torch.Tensor

In [4]:
# check the dimension of the scalar
scalar.ndim

0

In [14]:
# Check the shape of the scalar
scalar.shape

torch.Size([])

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [21]:
torch.tensor([[[[[8,8,6], [4,6,8]]], [[[4,8,6], [7,3,8]]]]]).shape

torch.Size([1, 2, 1, 2, 3])

In [22]:
torch.tensor([[[[[8,8,6], [4,6,8]]]]]).ndim

5

In [10]:
# Matrix
MATRIX = torch.tensor([[4,5],
                      [9,10]])
MATRIX

tensor([[ 4,  5],
        [ 9, 10]])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX.ndim

2

## **Creating Random Tensors with Pytorch**

Why random tensors?

Ans: Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

this adjustment is done through backpropagation.

In [18]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.9999, 0.5095, 0.4767, 0.4655],
         [0.6371, 0.7230, 0.4825, 0.5172],
         [0.1832, 0.1626, 0.0225, 0.8327]]])

In [19]:
random_tensor.ndim

3

In [20]:
random_tensor.shape

torch.Size([1, 3, 4])

## **Zeros and Ones**

In [23]:
# Create tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros.ndim, zeros.shape

(2, torch.Size([3, 4]))

In [25]:
# Create tensopr of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## **Creating range of Tensors and Tensor-like**

In [28]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten.ndim, one_to_ten.shape

(1, torch.Size([10]))